#############################################################################
# Makefile for building: Scintilla_test
# Generated by qmake (3.1) (Qt 5.9.7)
# Project:  Scintilla_test.pro
# Template: app
# Command: /media/lbt/_dde_data/software/Anaconda3/bin/qmake -o Makefile Scintilla_test.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQSCINTILLA_DLL -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -IScintilla -I/media/lbt/_dde_data/software/Anaconda3/include/qt -I/media/lbt/_dde_data/software/Anaconda3/include/qt/QtPrintSupport -I/media/lbt/_dde_data/software/Anaconda3/include/qt/QtWidgets -I/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui -I/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore -I. -I/media/lbt/_dde_data/software/Anaconda3/mkspecs/linux-g++
QMAKE         = /media/lbt/_dde_data/software/Anaconda3/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /media/lbt/_dde_data/software/Anaconda3/bin/qmake -install qinstall
QINSTALL_PROGRAM = /media/lbt/_dde_data/software/Anaconda3/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Scintilla_test1.0.0
DISTDIR = /home/lbt/Scintilla_test/.tmp/Scintilla_test1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/media/lbt/_dde_data/software/Anaconda3/lib
LIBS          = $(SUBLIBS) -L/home/lbt/Scintilla_test/Scintilla/ -L/media/lbt/_dde_data/software/Anaconda3/lib -lqscintilla2_qt5 -lQt5PrintSupport -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		moc_mainwindow.o
DIST          = /media/lbt/_dde_data/software/Anaconda3/mkspecs/features/spec_pre.prf \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/common/unix.conf \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/common/linux.conf \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/common/sanitize.conf \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/common/gcc-base.conf \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/common/gcc-base-unix.conf \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/common/g++-base.conf \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/common/g++-unix.conf \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/qconfig.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3danimation.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3danimation_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3dcore.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3dcore_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3dextras.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3dextras_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3dinput.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3dinput_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3dlogic.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3dquick.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3dquick_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3dquickextras.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3dquickinput.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3dquickrender.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3drender.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3drender_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_bluetooth.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_charts.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_charts_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_concurrent.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_concurrent_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_core.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_core_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_datavisualization.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_dbus.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_dbus_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_designer.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_designer_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_egl_support_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_fb_support_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_gamepad.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_gamepad_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_glx_support_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_gui.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_gui_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_help.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_help_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_input_support_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_location.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_location_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_multimedia.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_multimedia_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_network.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_network_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_networkauth.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_networkauth_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_nfc.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_nfc_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_opengl.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_opengl_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_openglextensions.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_positioning.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_positioning_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_printsupport.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_printsupport_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_purchasing.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_purchasing_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_qml.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_qml_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_qmltest.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_qmltest_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_quick.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_quick_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_quickwidgets.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_remoteobjects.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_repparser.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_repparser_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_script.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_script_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_scripttools.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_scripttools_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_scxml.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_scxml_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_sensors.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_sensors_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_serialbus.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_serialbus_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_serialport.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_serialport_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_service_support_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_sql.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_sql_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_svg.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_svg_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_testlib.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_testlib_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_texttospeech.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_theme_support_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_uiplugin.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_uitools.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_uitools_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_webchannel.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_webchannel_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_webengine.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_webengine_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_webenginecore.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_websockets.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_websockets_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_webview.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_webview_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_widgets.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_widgets_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_x11extras.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_x11extras_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_xml.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_xml_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/qt_functions.prf \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/qt_config.prf \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/linux-g++/qmake.conf \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/spec_post.prf \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/exclusive_builds.prf \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/toolchain.prf \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/default_pre.prf \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/resolve_config.prf \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/default_post.prf \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/qscintilla2.prf \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/warn_on.prf \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/qt.prf \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/resources.prf \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/moc.prf \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/unix/opengl.prf \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/uic.prf \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/unix/thread.prf \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/qmake_use.prf \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/file_copies.prf \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/testcase_targets.prf \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/exceptions.prf \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/yacc.prf \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/lex.prf \
		Scintilla_test.pro mainwindow.h main.cpp \
		mainwindow.cpp
QMAKE_TARGET  = Scintilla_test
DESTDIR       = 
TARGET        = Scintilla_test


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Scintilla_test.pro /media/lbt/_dde_data/software/Anaconda3/mkspecs/linux-g++/qmake.conf /media/lbt/_dde_data/software/Anaconda3/mkspecs/features/spec_pre.prf \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/common/unix.conf \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/common/linux.conf \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/common/sanitize.conf \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/common/gcc-base.conf \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/common/gcc-base-unix.conf \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/common/g++-base.conf \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/common/g++-unix.conf \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/qconfig.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3danimation.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3danimation_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3dcore.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3dcore_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3dextras.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3dextras_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3dinput.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3dinput_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3dlogic.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3dquick.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3dquick_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3dquickextras.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3dquickinput.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3dquickrender.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3drender.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3drender_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_bluetooth.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_charts.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_charts_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_concurrent.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_concurrent_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_core.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_core_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_datavisualization.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_dbus.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_dbus_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_designer.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_designer_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_egl_support_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_fb_support_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_gamepad.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_gamepad_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_glx_support_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_gui.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_gui_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_help.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_help_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_input_support_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_location.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_location_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_multimedia.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_multimedia_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_network.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_network_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_networkauth.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_networkauth_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_nfc.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_nfc_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_opengl.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_opengl_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_openglextensions.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_positioning.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_positioning_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_printsupport.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_printsupport_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_purchasing.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_purchasing_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_qml.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_qml_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_qmltest.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_qmltest_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_quick.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_quick_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_quickwidgets.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_remoteobjects.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_repparser.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_repparser_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_script.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_script_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_scripttools.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_scripttools_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_scxml.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_scxml_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_sensors.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_sensors_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_serialbus.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_serialbus_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_serialport.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_serialport_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_service_support_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_sql.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_sql_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_svg.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_svg_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_testlib.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_testlib_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_texttospeech.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_theme_support_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_uiplugin.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_uitools.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_uitools_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_webchannel.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_webchannel_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_webengine.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_webengine_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_webenginecore.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_websockets.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_websockets_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_webview.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_webview_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_widgets.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_widgets_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_x11extras.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_x11extras_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_xml.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_xml_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/qt_functions.prf \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/qt_config.prf \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/linux-g++/qmake.conf \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/spec_post.prf \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/exclusive_builds.prf \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/toolchain.prf \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/default_pre.prf \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/resolve_config.prf \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/default_post.prf \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/qscintilla2.prf \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/warn_on.prf \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/qt.prf \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/resources.prf \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/moc.prf \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/unix/opengl.prf \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/uic.prf \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/unix/thread.prf \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/qmake_use.prf \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/file_copies.prf \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/testcase_targets.prf \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/exceptions.prf \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/yacc.prf \
		/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/lex.prf \
		Scintilla_test.pro \
		/media/lbt/_dde_data/software/Anaconda3/lib/libQt5PrintSupport.prl \
		/media/lbt/_dde_data/software/Anaconda3/lib/libQt5Widgets.prl \
		/media/lbt/_dde_data/software/Anaconda3/lib/libQt5Gui.prl \
		/media/lbt/_dde_data/software/Anaconda3/lib/libQt5Core.prl
	$(QMAKE) -o Makefile Scintilla_test.pro
/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/spec_pre.prf:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/common/unix.conf:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/common/linux.conf:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/common/sanitize.conf:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/common/gcc-base.conf:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/common/gcc-base-unix.conf:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/common/g++-base.conf:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/common/g++-unix.conf:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/qconfig.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3danimation.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3danimation_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3dcore.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3dcore_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3dextras.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3dextras_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3dinput.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3dinput_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3dlogic.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3dlogic_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3dquick.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3dquick_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3dquickanimation.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3dquickextras.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3dquickinput.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3dquickrender.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3drender.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_3drender_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_bluetooth.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_bluetooth_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_bootstrap_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_charts.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_charts_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_concurrent.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_concurrent_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_core.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_core_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_datavisualization.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_datavisualization_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_dbus.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_dbus_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_designer.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_designer_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_designercomponents_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_egl_support_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_fb_support_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_gamepad.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_gamepad_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_glx_support_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_gui.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_gui_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_help.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_help_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_input_support_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_location.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_location_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_multimedia.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_multimedia_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_multimediawidgets.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_network.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_network_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_networkauth.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_networkauth_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_nfc.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_nfc_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_opengl.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_opengl_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_openglextensions.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_openglextensions_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_positioning.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_positioning_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_printsupport.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_printsupport_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_purchasing.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_purchasing_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_qml.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_qml_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_qmldebug_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_qmltest.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_qmltest_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_quick.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_quick_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_quickcontrols2.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_quickparticles_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_quickwidgets.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_remoteobjects.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_repparser.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_repparser_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_script.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_script_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_scripttools.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_scripttools_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_scxml.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_scxml_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_sensors.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_sensors_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_serialbus.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_serialbus_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_serialport.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_serialport_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_service_support_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_sql.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_sql_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_svg.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_svg_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_testlib.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_testlib_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_texttospeech.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_texttospeech_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_theme_support_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_uiplugin.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_uitools.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_uitools_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_webchannel.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_webchannel_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_webengine.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_webengine_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_webenginecore.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_webenginecore_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_webenginewidgets.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_websockets.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_websockets_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_webview.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_webview_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_widgets.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_widgets_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_x11extras.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_x11extras_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_xml.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_xml_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_xmlpatterns.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/qt_functions.prf:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/qt_config.prf:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/linux-g++/qmake.conf:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/spec_post.prf:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/exclusive_builds.prf:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/toolchain.prf:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/default_pre.prf:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/resolve_config.prf:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/default_post.prf:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/qscintilla2.prf:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/warn_on.prf:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/qt.prf:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/resources.prf:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/moc.prf:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/unix/opengl.prf:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/uic.prf:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/unix/thread.prf:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/qmake_use.prf:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/file_copies.prf:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/testcase_targets.prf:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/exceptions.prf:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/yacc.prf:
/media/lbt/_dde_data/software/Anaconda3/mkspecs/features/lex.prf:
Scintilla_test.pro:
/media/lbt/_dde_data/software/Anaconda3/lib/libQt5PrintSupport.prl:
/media/lbt/_dde_data/software/Anaconda3/lib/libQt5Widgets.prl:
/media/lbt/_dde_data/software/Anaconda3/lib/libQt5Gui.prl:
/media/lbt/_dde_data/software/Anaconda3/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Scintilla_test.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /media/lbt/_dde_data/software/Anaconda3/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /media/lbt/_dde_data/software/Anaconda3/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -Wall -W -dM -E -o moc_predefs.h /media/lbt/_dde_data/software/Anaconda3/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: /media/lbt/_dde_data/software/Anaconda3/include/qt/QtWidgets/QMainWindow \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtWidgets/qmainwindow.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtWidgets/qtwidgetsglobal.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qtguiglobal.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qglobal.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qconfig-bootstrapped.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qconfig.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qtcore-config.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qsystemdetection.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qprocessordetection.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qcompilerdetection.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qtypeinfo.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qsysinfo.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qlogging.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qflags.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qatomic.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qbasicatomic.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qatomic_bootstrap.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qgenericatomic.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qatomic_cxx11.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qatomic_msvc.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qglobalstatic.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qmutex.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qnumeric.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qversiontagging.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qtgui-config.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtWidgets/qtwidgets-config.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtWidgets/qwidget.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qwindowdefs.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qobjectdefs.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qnamespace.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qobjectdefs_impl.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qwindowdefs_win.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qobject.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qstring.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qchar.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qbytearray.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qrefcount.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qarraydata.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qstringbuilder.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qlist.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qalgorithms.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qiterator.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qhashfunctions.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qpair.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qbytearraylist.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qstringlist.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qregexp.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qstringmatcher.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qcoreevent.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qscopedpointer.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qmetatype.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qvarlengtharray.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qcontainerfwd.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qobject_impl.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qmargins.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qpaintdevice.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qrect.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qsize.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qpoint.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qpalette.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qcolor.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qrgb.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qrgba64.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qbrush.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qvector.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qmatrix.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qpolygon.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qregion.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qdatastream.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qiodevice.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qline.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qtransform.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qpainterpath.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qimage.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qpixelformat.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qpixmap.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qsharedpointer.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qshareddata.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qhash.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qsharedpointer_impl.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qfont.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qfontmetrics.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qfontinfo.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtWidgets/qsizepolicy.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qcursor.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qkeysequence.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qevent.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qvariant.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qmap.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qdebug.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qtextstream.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qlocale.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qset.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qcontiguouscache.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qurl.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qurlquery.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qfile.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qfiledevice.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qvector2d.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qtouchdevice.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtWidgets/qtabwidget.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qicon.h \
		Scintilla/Qsci/qsciscintilla.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/QByteArray \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/QList \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/QObject \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/QPointer \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qpointer.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/QStringList \
		Scintilla/Qsci/qsciglobal.h \
		Scintilla/Qsci/qscicommand.h \
		Scintilla/Qsci/qsciscintillabase.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtWidgets/QAbstractScrollArea \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtWidgets/qabstractscrollarea.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtWidgets/qframe.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/QPoint \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/QTimer \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qtimer.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qbasictimer.h \
		Scintilla/Qsci/qscidocument.h \
		mainwindow.h \
		moc_predefs.h \
		/media/lbt/_dde_data/software/Anaconda3/bin/moc
	/media/lbt/_dde_data/software/Anaconda3/bin/moc $(DEFINES) --include ./moc_predefs.h -I/media/lbt/_dde_data/software/Anaconda3/mkspecs/linux-g++ -I/home/lbt/Scintilla_test -I/home/lbt/Scintilla_test/Scintilla -I/media/lbt/_dde_data/software/Anaconda3/include/qt -I/media/lbt/_dde_data/software/Anaconda3/include/qt/QtPrintSupport -I/media/lbt/_dde_data/software/Anaconda3/include/qt/QtWidgets -I/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui -I/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include mainwindow.h -o moc_mainwindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtWidgets/QMainWindow \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtWidgets/qmainwindow.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtWidgets/qtwidgetsglobal.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qtguiglobal.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qglobal.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qconfig-bootstrapped.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qconfig.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qtcore-config.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qsystemdetection.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qprocessordetection.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qcompilerdetection.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qtypeinfo.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qsysinfo.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qlogging.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qflags.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qatomic.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qbasicatomic.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qatomic_bootstrap.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qgenericatomic.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qatomic_cxx11.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qatomic_msvc.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qglobalstatic.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qmutex.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qnumeric.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qversiontagging.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qtgui-config.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtWidgets/qtwidgets-config.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtWidgets/qwidget.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qwindowdefs.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qobjectdefs.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qnamespace.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qobjectdefs_impl.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qwindowdefs_win.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qobject.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qstring.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qchar.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qbytearray.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qrefcount.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qarraydata.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qstringbuilder.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qlist.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qalgorithms.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qiterator.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qhashfunctions.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qpair.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qbytearraylist.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qstringlist.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qregexp.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qstringmatcher.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qcoreevent.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qscopedpointer.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qmetatype.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qvarlengtharray.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qcontainerfwd.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qobject_impl.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qmargins.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qpaintdevice.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qrect.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qsize.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qpoint.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qpalette.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qcolor.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qrgb.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qrgba64.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qbrush.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qvector.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qmatrix.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qpolygon.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qregion.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qdatastream.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qiodevice.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qline.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qtransform.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qpainterpath.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qimage.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qpixelformat.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qpixmap.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qsharedpointer.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qshareddata.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qhash.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qsharedpointer_impl.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qfont.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qfontmetrics.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qfontinfo.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtWidgets/qsizepolicy.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qcursor.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qkeysequence.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qevent.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qvariant.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qmap.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qdebug.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qtextstream.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qlocale.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qset.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qcontiguouscache.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qurl.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qurlquery.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qfile.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qfiledevice.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qvector2d.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qtouchdevice.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtWidgets/qtabwidget.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qicon.h \
		Scintilla/Qsci/qsciscintilla.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/QByteArray \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/QList \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/QObject \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/QPointer \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qpointer.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/QStringList \
		Scintilla/Qsci/qsciglobal.h \
		Scintilla/Qsci/qscicommand.h \
		Scintilla/Qsci/qsciscintillabase.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtWidgets/QAbstractScrollArea \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtWidgets/qabstractscrollarea.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtWidgets/qframe.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/QPoint \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/QTimer \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qtimer.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qbasictimer.h \
		Scintilla/Qsci/qscidocument.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtWidgets/QApplication \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtWidgets/qapplication.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qcoreapplication.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qeventloop.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtWidgets/qdesktopwidget.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qguiapplication.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp /media/lbt/_dde_data/software/Anaconda3/include/qt/QtWidgets/QAction \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtWidgets/qaction.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtWidgets/qtwidgetsglobal.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qtguiglobal.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qglobal.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qconfig-bootstrapped.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qconfig.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qtcore-config.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qsystemdetection.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qprocessordetection.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qcompilerdetection.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qtypeinfo.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qsysinfo.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qlogging.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qflags.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qatomic.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qbasicatomic.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qatomic_bootstrap.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qgenericatomic.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qatomic_cxx11.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qatomic_msvc.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qglobalstatic.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qmutex.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qnumeric.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qversiontagging.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qtgui-config.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtWidgets/qtwidgets-config.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qkeysequence.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qstring.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qchar.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qbytearray.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qrefcount.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qnamespace.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qarraydata.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qstringbuilder.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qobjectdefs.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qobjectdefs_impl.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtWidgets/qwidget.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qwindowdefs.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qwindowdefs_win.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qobject.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qlist.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qalgorithms.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qiterator.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qhashfunctions.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qpair.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qbytearraylist.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qstringlist.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qregexp.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qstringmatcher.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qcoreevent.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qscopedpointer.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qmetatype.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qvarlengtharray.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qcontainerfwd.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qobject_impl.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qmargins.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qpaintdevice.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qrect.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qsize.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qpoint.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qpalette.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qcolor.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qrgb.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qrgba64.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qbrush.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qvector.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qmatrix.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qpolygon.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qregion.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qdatastream.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qiodevice.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qline.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qtransform.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qpainterpath.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qimage.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qpixelformat.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qpixmap.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qsharedpointer.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qshareddata.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qhash.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qsharedpointer_impl.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qfont.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qfontmetrics.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qfontinfo.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtWidgets/qsizepolicy.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qcursor.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qevent.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qvariant.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qmap.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qdebug.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qtextstream.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qlocale.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qset.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qcontiguouscache.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qurl.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qurlquery.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qfile.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qfiledevice.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qvector2d.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qtouchdevice.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qicon.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtWidgets/qactiongroup.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtWidgets/QApplication \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtWidgets/qapplication.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qcoreapplication.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qeventloop.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtWidgets/qdesktopwidget.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qguiapplication.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/qinputmethod.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/QCloseEvent \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/QFile \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/QFileInfo \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qfileinfo.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtWidgets/QFileDialog \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtWidgets/qfiledialog.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qdir.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtWidgets/qdialog.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/QIcon \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtWidgets/QMenu \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtWidgets/qmenu.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtWidgets/QMenuBar \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtWidgets/qmenubar.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtWidgets/QMessageBox \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtWidgets/qmessagebox.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/QPoint \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/QSettings \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qsettings.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/QSize \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtWidgets/QStatusBar \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtWidgets/qstatusbar.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/QTextStream \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtWidgets/QToolBar \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtWidgets/qtoolbar.h \
		Scintilla/Qsci/qsciscintilla.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/QByteArray \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/QList \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/QObject \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/QPointer \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qpointer.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/QStringList \
		Scintilla/Qsci/qsciglobal.h \
		Scintilla/Qsci/qscicommand.h \
		Scintilla/Qsci/qsciscintillabase.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtWidgets/QAbstractScrollArea \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtWidgets/qabstractscrollarea.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtWidgets/qframe.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/QTimer \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qtimer.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/qbasictimer.h \
		Scintilla/Qsci/qscidocument.h \
		Scintilla/Qsci/qscilexercpp.h \
		Scintilla/Qsci/qscilexer.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/QColor \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtGui/QFont \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/QMap \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/QString \
		Scintilla/Qsci/qscilexerpython.h \
		Scintilla/Qsci/qsciapis.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtCore/QPair \
		Scintilla/Qsci/qsciabstractapis.h \
		mainwindow.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtWidgets/QMainWindow \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtWidgets/qmainwindow.h \
		/media/lbt/_dde_data/software/Anaconda3/include/qt/QtWidgets/qtabwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/Scintilla_test/bin || mkdir -p $(INSTALL_ROOT)/opt/Scintilla_test/bin
	-$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/Scintilla_test/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/Scintilla_test/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/Scintilla_test/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/Scintilla_test/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

